server:
  port: 8080
  shutdown: graceful

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          inventory-service:
            connect-timeout: 2000   # 2 sec
            read-timeout: 3000      # 3 sec
            logger-level: full
  application:
    name: product-service

resilience4j:
  circuitbreaker:
    instances:
      inventoryCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

  timelimiter:
    instances:
      inventoryTL:
        timeoutDuration: 2s

  bulkhead:
    instances:
      inventoryBH:
        maxConcurrentCalls: 10
        maxWaitDuration: 0

  retry:
    instances:
      inventoryRetry:
        maxAttempts: 2
        waitDuration: 500ms
eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      resilience4j.circuitbreaker: true
      resilience4j.retry: true
logging:
  pattern:
    level: "%5p [traceId=%X{traceId}, spanId=%X{spanId}]"
