server:
  port: 8081

spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: inventory-service
eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
