apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiGateWay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apiGateWay
  template:
    metadata:
      labels:
        app: apiGateWay
    spec:
      containers:
        - name: apiGateWay
          image: ./api-gateway:latest
          ports:
            - containerPort: 8082
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: apiGateWay
spec:
  selector:
    app: apiGateWay
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
